### ISSUE TITLE
Not working with afk detector.

### ISSUE THREAD

**Issue by Deeptanil** [SuperDyl/tag-game#1]
The red name get removed once someone goes afk. Opening issue on the afk datapack as well. 
Not sure what you can do other than keep checking that their team is the same.
https://modrinth.com/datapack/detect-afk

**Comment by SuperDyl** [comment]
Definitely an interesting case. I can think of a couple work arounds for this, such as giving tagged players a tag to go with the team and creating a function group for resetting player teams. I’ll have to mess with some of these options, because it should be pretty easy to add compatibility with datapacks like this, even if I do have to resort to checking every tick

**Comment by Deeptanil** [comment]
If not every tick definitely every couple of ticks.. or even just checking if any players teams have been changed.

fyi heres the issue opened on the afk datapacks git: https://github.com/clo4/datapacks/issues/31

**Comment by clo4** [comment]
Hey hey! First of all, love the concept behind this data pack - funny enough I actually made the AFK data packs for a similar reason, initially because Vanilla Tweaks wasn't as efficient as I wanted and it didn't support all the features I needed. Both of us ended up entirely reimplementing the concepts haha.

So my understanding is that since [AFK Dim Names](https://modrinth.com/datapack/afk-dim-names) is super naive and just sets a player's team without doing any checks, and the game doesn't support a way to *get* a player's team, it overwrites the player team and doesn't restore it. If a player is on the `tg_tagged` team and goes AFK, game breaks.

I honestly think the solution is more on my side than yours, I can make it not override a player's team if they're on one already, easy as `execute if entity @s[team=]`. Frankly I should have done this already :P

If you have another idea feel free to keep the issue open, but otherwise, I think you can close this.

**Comment by SuperDyl** [comment]
@Deeptanil , I'm glad you brought this to my attention because this bug could break the tag game, even with the Vanilla Tweaks datapack (since Vanilla Tweaks removed the code to return the player back to the tagger team).

@clo4 , yes, checking if the player already has a team would probably be a quick fix to this problem in the future. I've made it changing the team for tagger still allows them to tag players, so it isn't necessary for compatibility with my specific datapack anymore.
